config/routes.rb
Rails.application.routes.draw do
  root 'top#index'
  resources :categories
  resources :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_one :item
end

app/models/item.rb
class Item < ApplicationRecord
    belongs_to :category, optional: true


    def self.search(search)
        if search.present?
            Item.where(['name LIKE ?', "%#{search}%"])
        else
            Item.all
        end
    end
end

app/models/s3image.rb
class S3image < ApplicationRecord
    mount_uploader :file_name, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # Basic認証フィルタを対象アクションに指定
  http_basic_authenticate_with :name => 'a', :password => 'a'

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # Basic認証フィルタを対象アクションに指定
  http_basic_authenticate_with :name => 'a', :password => 'a', :only => :new

  require 'pp'

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    @items = @items.where!("name LIKE ?", "%#{params[:name]}%") if params[:name]
    @items = @items.where!(category_id: params[:category_id]) if params[:category_id]
    @items = @items.where!(collaboration: params[:collaboration]) if params[:collaboration]
    @items = @items.where!(release_date: params[:start_date]..params[:end_date]) if params[:start_date]..params[:end_date]
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(params.require(:item).permit(:name,:price,:release_date,:category_id,:collaboration,:description,:image_path))

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :price, :release_date, :category, :collaboration, :description, :image_path)
    end
end

app/controllers/s3images_controller.rb
class S3imagesController < ApplicationController
  before_action :set_s3image, only: [:show, :edit, :update, :destroy]

  # GET /s3images
  # GET /s3images.json
  def index
    @s3images = S3image.all
  end

  # GET /s3images/1
  # GET /s3images/1.json
  def show
  end

  # GET /s3images/new
  def new
    @s3image = S3image.new
  end

  # GET /s3images/1/edit
  def edit
  end

  # POST /s3images
  # POST /s3images.json
  def create
    @s3image = S3image.new(s3image_params)

    respond_to do |format|
      if @s3image.save
        format.html { redirect_to @s3image, notice: 'S3image was successfully created.' }
        format.json { render :show, status: :created, location: @s3image }
      else
        format.html { render :new }
        format.json { render json: @s3image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /s3images/1
  # PATCH/PUT /s3images/1.json
  def update
    respond_to do |format|
      if @s3image.update(s3image_params)
        format.html { redirect_to @s3image, notice: 'S3image was successfully updated.' }
        format.json { render :show, status: :ok, location: @s3image }
      else
        format.html { render :edit }
        format.json { render json: @s3image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /s3images/1
  # DELETE /s3images/1.json
  def destroy
    @s3image.destroy
    respond_to do |format|
      format.html { redirect_to s3images_url, notice: 'S3image was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_s3image
      @s3image = S3image.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def s3image_params
      params.require(:s3image).permit(:title, :file_name, :comment)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/s3images_helper.rb
module S3imagesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to '編集', edit_category_path(category) %></td>
        <td><%= link_to '削除', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :release_date %>
    <%= form.text_field :release_date %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.number_field :category_id %>
  </div>

  <div class="field">
    <%= form.label :collaboration %>
    <%= form.text_field :collaboration %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image_path %>
    <%= form.text_field :image_path %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<div class="body-frame">

      <div class="d-flex justify-content-center"><% @items.each do |item| %>
      <div class="group">
            <%= link_to item do %>
            <%= image_tag("#{item.image_path}") %>
            <% end %>
            <p><%= item.name %></p>
      </div>
            <td><%#= item.release_date %></td>
            <td><%#= item.category.name %></td>
            <td><%#= item.collaboration %></td>
            <td><%#= item.description %></td>
            <td><%#= item.image_path %></td>
            <td><%#= link_to 'Show', item %></td>
            <td><%#= link_to 'Edit', edit_item_path(item) %></td>
            <td><%#= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
      </div>

      <br>

  <%#= link_to 'New Item', new_item_path %>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<div class="body-frame">
<p id="notice"><%= notice %></p>

<div class="item_frame">

      <p>
        <%= @item.name %>
      </p>
<div class="item_flex">
<%= image_tag("#{@item.image_path}") %>
 <div class="item_details">
      <p>
        <strong>Price:</strong>
        <%= @item.price %>
      </p>

      <p>
        <strong>Release date:</strong>
        <%= @item.release_date %>
      </p>

      <p>
        <strong>Category:</strong>
        <%= @item.category.name %>
      </p>

      <p>
        <strong>Collaboration:</strong>
        <%= @item.collaboration %>
      </p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>
</div>
</div>
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SupremeArchive</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class="fixed-top">
      <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
          <a class="navbar-brand" href="http://localhost:3000/">
            <%= image_tag 'sa-image.jpg', :size =>"70x70", class: "logo" %>
            <%# <img src="assets/sa-image.jpg" width="70" height="70" class="d-inline-block align-top" alt="logo"> %>
              <h1>Supreme Archive</h1>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown" >
              <ul class="navbar-nav">
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Category
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <%# <a class="dropdown-item" href="#">jackets</a> %>
                        <%= link_to 'jackets',items_path(category_id:1),class:"dropdown-item" %>
                        <%= link_to 'shirts',items_path(category_id:2),class:"dropdown-item" %>
                        <%= link_to 'tops/sweaters',items_path(category_id:3),class:"dropdown-item" %>
                        <%= link_to 'sweatshirts',items_path(category_id:4),class:"dropdown-item" %>
                        <%= link_to 'pants',items_path(category_id:5),class:"dropdown-item" %>
                        <%= link_to 'shorts',items_path(category_id:6),class:"dropdown-item" %>
                        <%= link_to 't-shirts',items_path(category_id:7),class:"dropdown-item" %>
                        <%= link_to 'hats',items_path(category_id:8),class:"dropdown-item" %>
                        <%= link_to 'bags',items_path(category_id:9),class:"dropdown-item" %>
                        <%= link_to 'accessories',items_path(category_id:10),class:"dropdown-item" %>
                        <%= link_to 'skate',items_path(category_id:11),class:"dropdown-item" %>
                      </div>
                  </li>
                  <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      Collaboration
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <%# <a class="dropdown-item" href="#">NIKE</a> %>
                        <%= link_to 'NIKE',items_path(collaboration:'NIKE'),class:"dropdown-item" %>
                        <%= link_to 'THE NORTH FACE',items_path(collaboration:'THE NORTH FACE'),class:"dropdown-item" %>
                        <%= link_to 'LOUIS VUITTON',items_path(collaboration:'LOUIS VUITTON'),class:"dropdown-item" %>
                        <%= link_to 'LACOSTE',items_path(collaboration:'LACOSTE'),class:"dropdown-item" %>
                        <%= link_to 'adidas',items_path(collaboration:'adidas'),class:"dropdown-item" %>
                        <%= link_to 'jordan',items_path(collaboration:'jordan'),class:"dropdown-item" %>
                        <%= link_to 'Off-White',items_path(collaboration:'Off-White'),class:"dropdown-item" %>
                        <%= link_to 'Vans',items_path(collaboration:'Vans'),class:"dropdown-item" %>
                        <%= link_to 'Stussy',items_path(collaboration:'Stussy'),class:"dropdown-item" %>
                        <%= link_to 'Champion',items_path(collaboration:'Champion'),class:"dropdown-item" %>
                        <%= link_to 'KAWS',items_path(collaboration:'KAWS'),class:"dropdown-item" %>
                      </div>
                  </li>
              </ul>
          </div>
          <%= form_with url: items_path, method: :get, class: "top-right", local: true do |f| %>
              <%= f.text_field :name %>
              <%= f.submit :search %>
          <% end %>
      </nav>
    </div>
    <br>
    <br>
    <%= yield %>
  </body>
</html>

<div id="sidebar">
  <a class="twitter-timeline" data-width="300" data-height="500" data-theme="dark" href="https://twitter.com/Supreme__news?ref_src=twsrc%5Etfw">Tweets by Supreme__news</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</div>

app/views/s3images/_form.html.erb
<%= form_with(model: s3image, local: true) do |form| %>
  <% if s3image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(s3image.errors.count, "error") %> prohibited this s3image from being saved:</h2>

      <ul>
      <% s3image.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :file_name %>
    <%= form.file_field :file_name %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/s3images/edit.html.erb
<h1>Editing S3image</h1>

<%= render 'form', s3image: @s3image %>

<%= link_to 'Show', @s3image %> |
<%= link_to 'Back', s3images_path %>

app/views/s3images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>S3images</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>File name</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @s3images.each do |s3image| %>
      <tr>
        <td><%= s3image.title %></td>
        <td><%= s3image.file_name %></td>
        <td><%= s3image.comment %></td>
        <td><%= link_to 'Show', s3image %></td>
        <td><%= link_to 'Edit', edit_s3image_path(s3image) %></td>
        <td><%= link_to 'Destroy', s3image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New S3image', new_s3image_path %>

app/views/s3images/new.html.erb
<h1>New S3image</h1>

<%= render 'form', s3image: @s3image %>

<%= link_to 'Back', s3images_path %>

app/views/s3images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @s3image.title %>
</p>

<p>
  <strong>File name:</strong>
  <%= @s3image.file_name %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @s3image.comment %>
</p>

<%= link_to 'Edit', edit_s3image_path(@s3image) %> |
<%= link_to 'Back', s3images_path %>

app/views/top/index.html.erb
<body>
    <div class="body-frame">
        <div class=frame>
            <div class=top-frame>
                <h1>Release Seasons</h1>
            </div>
        </div>


        <div class="image-group-frame">
            <div class="image-group1-if">
                <div class="image-group1-icon">
                    <%= link_to image_tag("20fw.jpg"),items_path(start_date:"2020-08-01",end_date:"2021-01-31"),class:"image" %>
                </div>
                <p class="image-group-text">2020_feb</p>
            </div>
            <div class="image-group1-if">
                <div class="image-group1-icon">
                    <%= link_to image_tag("20ss.jpg"),items_path(start_date:"2020-02-01",end_date:"2020-07-31"),class:"image"%>
                </div>
                <p class="image-group-text">2020_jan</p>
            </div>
            <div class="image-group1-if">
                <div class="image-group1-icon">
                    <%= link_to image_tag("19fw.jpg"),items_path(start_date:"2019-08-01",end_date:"2020-01-31"),class:"image"%>
                </div>
                <p class="image-group-text">2019_dec</p>
            </div>
                        <div class="image-group1-if">
                <div class="image-group1-icon">
                    <%= link_to image_tag("19ss.jpg"),items_path(start_date:"2019-02-01",end_date:"2019-07-31"),class:"image"%>
                </div>
                <p class="image-group-text">2019_nov</p>
            </div>
            <div class="image-group1-if">
                <div class="image-group1-icon">
                    <%= link_to image_tag("18fw.jpg"),items_path(start_date:"2018-08-01",end_date:"2019-01-31"),class:"image"%>
                </div>
                <p class="image-group-text">2019_oct</p>
            </div>
            <div class="image-group1-if">
                <div class="image-group1-icon">
                    <%= link_to image_tag("18ss.jpg"),items_path(start_date:"2018-02-01",end_date:"2018-07-31"),class:"image"%>
                </div>
                <p class="image-group-text">2019_sep</p>
            </div>
        </div>
    </div>
</body>